-- Drop current INTERESTS and STUDENTS tables if they exist
DROP TABLE IF EXISTS INTERESTS;
DROP TABLE IF EXISTS STUDENTS;

-- Rename *_blue tables back to their original names
ALTER TABLE INTERESTS_blue RENAME TO INTERESTS;
ALTER TABLE STUDENTS_blue RENAME TO STUDENTS;

SELECT * FROM STUDENTS;
SELECT * FROM INTERESTS;
